import { readFile, writeFile, rename, mkdir, unlink } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import sharp from "sharp";
import { dateFromFilename } from "../lib/photo-date";
import { findPhotoSourceFiles, resolvePhotoSourcePath } from "./photo-source-files";

export interface ManifestPhoto {
  readonly id: string;
  readonly source: string;
  readonly width: number;
  readonly height: number;
  readonly date?: string;
}

export async function scanPhotoManifest(root: string): Promise<ManifestPhoto[]> {
  const files = await findPhotoSourceFiles(root);
  const seen = new Map<string, string>();
  const records: ManifestPhoto[] = [];
  for (const file of files) {
    resolvePhotoSourcePath(root, file.relativePath);
    const segments = file.relativePath.split("/");
    const project = segments[0];
    const basename = path.basename(file.relativePath, path.extname(file.relativePath));
    if (segments.length < 2 || !/^[a-z0-9-]+$/.test(project) || !/^[a-z0-9-]+$/.test(basename)) {
      throw new Error(`${file.relativePath}: require a project directory and lowercase [a-z0-9-]+ names`);
    }
    const id = `${project}-${basename}`;
    if (seen.has(id)) throw new Error(`${id}: duplicate asset ID: ${seen.get(id)} and ${file.relativePath}`);
    seen.set(id, file.relativePath);
    const date = dateFromFilename(basename);
    try {
      const metadata = await sharp(file.absolutePath).metadata();
      const size = metadata.autoOrient ?? metadata;
      if (!size.width || !size.height) throw new Error("missing dimensions");
      records.push({ id, source: file.relativePath, width: size.width, height: size.height, ...(date ? { date } : {}) });
    } catch (error) {
      throw new Error(`${file.relativePath}: cannot read photo; ensure Git LFS files are downloaded. ${String(error)}`);
    }
  }
  return records.sort((a, b) => a.id < b.id ? -1 : a.id > b.id ? 1 : 0);
}

export async function writeIfChanged(filename: string, contents: string): Promise<void> {
  try { if (await readFile(filename, "utf8") === contents) return; } catch { /* First generation. */ }
  await mkdir(path.dirname(filename), { recursive: true });
  const temporary = `${filename}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporary, contents);
    await rename(temporary, filename);
  } finally {
    await unlink(temporary).catch(() => {});
  }
}

export async function generatePhotoManifest(root = process.cwd()): Promise<ManifestPhoto[]> {
  const records = await scanPhotoManifest(path.join(root, "assets/source/photos"));
  const entries = records.map((photo) => `  ${JSON.stringify(photo.id)}: ${JSON.stringify(photo)},`).join("\n");
  await writeIfChanged(path.join(root, "content/photo-manifest.generated.ts"),
    `// Generated by npm run photos:manifest. Do not edit.\nexport const photoManifest = {\n${entries}\n} as const;\n\nexport type PhotoAssetId = keyof typeof photoManifest;\n`);
  return records;
}
